{"version":3,"sources":["pages/learn-promises/examples/catch.mjs"],"names":["catchFn","Promise","resolve","reject","catch","e","console","log","Error","then","x"],"mappings":"6JAAe,SAASA,IACtB,IAAIC,SAAQ,SAACC,EAASC,GAAV,OAAqBA,EAAO,qBACrCC,OAAM,SAAAC,GAAC,OAAIC,QAAQC,IAAIF,MAE1B,IAAIJ,SAAQ,WACV,MAAM,IAAIO,MAAM,kCACfJ,OAAM,SAAAC,GAAC,OAAIC,QAAQC,IAAIF,MAE1B,IAAIJ,SAAQ,SAAAC,GAAO,OAAIA,EAAQ,MAC5BO,MAAK,SAAAC,GAAC,OAAQ,EAAJA,KACVD,MAAK,kBAAMR,QAAQE,OAAO,gCAC1BC,OAAM,SAAAC,GAAC,OAAIC,QAAQC,IAAIF,MACvBI,MAAK,kBAAMH,QAAQC,IAAI,4BAG1B,IAAIN,SAAQ,SAAAC,GAAO,OAAIA,EAAQ,MAC5BO,MAAK,kBAAMR,QAAQE,OAAO,gCAC1BC,OAAM,kBAAM,KACZK,MAAK,SAAAC,GAAC,OAAQ,EAAJA,KACVD,MAAK,SAAAC,GAAC,OAAIJ,QAAQC,IAAIG,MAnB3B","file":"static/js/9.5df56fa4.chunk.js","sourcesContent":["export default function catchFn() {\r\n  new Promise((resolve, reject) => reject('reject promise'))\r\n    .catch(e => console.log(e));\r\n\r\n  new Promise(() => {\r\n    throw new Error('throw an error from promise');\r\n  }).catch(e => console.log(e));\r\n\r\n  new Promise(resolve => resolve(2))\r\n    .then(x => x * 2)\r\n    .then(() => Promise.reject('reject from promise chain'))\r\n    .catch(e => console.log(e))\r\n    .then(() => console.log('will never be reached'))\r\n  ;\r\n\r\n  new Promise(resolve => resolve(2))\r\n    .then(() => Promise.reject('reject from promise chain'))\r\n    .catch(() => 2) // Catch an error and continue the chain.\r\n    .then(x => x * 2)\r\n    .then(x => console.log(x))\r\n  ;\r\n};\r\n"],"sourceRoot":""}